# Generated by Django 6.0 on 2025-12-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_note_color_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="author",
            new_name="user",
        ),
    ]
