# Generated by Django 6.0 on 2025-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_user_noteimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="note",
            name="note_id",
        ),
        migrations.AddField(
            model_name="note",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(default="ffffff", max_length=6),
        ),
        migrations.DeleteModel(
            name="NoteImage",
        ),
    ]
