# Generated by Django 6.0 on 2025-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_note_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
