# Generated by Django 6.0 on 2025-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_noteimage_image_alter_profile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="have_images",
            field=models.BooleanField(default=False),
        ),
    ]
