# Generated by Django 6.0 on 2025-12-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_note_have_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="have_images",
        ),
    ]
